// Army fitness test standards, loaded from the official score tables
// (assets/pt_standards/*.json, generated by tool/pt_standards/). The scoring
// rules here are generic, so a new test or new tables only need a new JSON
// file registered in standards.dart.

enum Sex { male, female }

/// General (combat-enabling): sex- and age-normed. Combat: sex-neutral
/// (uses the male/combat column), higher minimum total.
enum StandardType { general, combat }

enum EventUnit { lbs, reps, time }

class AgeGroup {
  final String label;
  final int min;
  final int? max;

  const AgeGroup({required this.label, required this.min, this.max});

  bool contains(int age) => age >= min && (max == null || age <= max!);

  factory AgeGroup.fromJson(Map<String, dynamic> json) =>
      AgeGroup(label: json['label'], min: json['min'], max: json['max']);
}

class ScoreRow {
  final int points;

  /// Raw-score threshold per age group; null where the tables show "---"
  /// (that point value can't be earned).
  final List<int?> male;
  final List<int?> female;

  const ScoreRow({
    required this.points,
    required this.male,
    required this.female,
  });

  factory ScoreRow.fromJson(Map<String, dynamic> json) => ScoreRow(
    points: json['points'],
    male: (json['male'] as List).cast<int?>(),
    female: (json['female'] as List).cast<int?>(),
  );
}

class PtEvent {
  final String id;
  final String name;
  final EventUnit unit;

  /// true: more is better (weight, reps, plank time); false: less is better
  /// (sprint-drag-carry and run times).
  final bool higherIsBetter;

  /// Highest points first.
  final List<ScoreRow> table;

  const PtEvent({
    required this.id,
    required this.name,
    required this.unit,
    required this.higherIsBetter,
    required this.table,
  });

  factory PtEvent.fromJson(Map<String, dynamic> json) {
    final table =
        (json['table'] as List)
            .map((r) => ScoreRow.fromJson(r as Map<String, dynamic>))
            .toList()
          ..sort((a, b) => b.points.compareTo(a.points));
    return PtEvent(
      id: json['id'],
      name: json['name'],
      unit: EventUnit.values.byName(json['unit']),
      higherIsBetter: json['better'] == 'higher',
      table: table,
    );
  }

  bool get isTimed => unit == EventUnit.time;

  /// Points for [raw] (lbs, reps, or seconds): the highest point value
  /// whose threshold is met; 0 if none is.
  int score(int raw, {required int column, required bool useMale}) {
    for (final row in table) {
      final threshold = (useMale ? row.male : row.female)[column];
      if (threshold == null) continue;
      final met = higherIsBetter ? raw >= threshold : raw <= threshold;
      if (met) return row.points;
    }
    return 0;
  }

  /// Raw score needed for at least [points] (e.g. the 60-point minimum).
  int? thresholdFor(int points, {required int column, required bool useMale}) {
    // Rows run high to low; the last row at or above [points] with a value
    // is the easiest way to earn them.
    int? best;
    for (final row in table) {
      if (row.points < points) break;
      final threshold = (useMale ? row.male : row.female)[column];
      if (threshold != null) best = threshold;
    }
    return best;
  }
}

/// Go/No-Go alternate aerobic event (for Soldiers with a profile).
class AlternateEvent {
  final String id;
  final String name;

  /// Maximum time in seconds per age group.
  final List<int> male;
  final List<int> female;

  const AlternateEvent({
    required this.id,
    required this.name,
    required this.male,
    required this.female,
  });

  factory AlternateEvent.fromJson(Map<String, dynamic> json) => AlternateEvent(
    id: json['id'],
    name: json['name'],
    male: (json['male'] as List).cast<int>(),
    female: (json['female'] as List).cast<int>(),
  );

  int maxSeconds({required int column, required bool useMale}) =>
      (useMale ? male : female)[column];

  bool isGo(int seconds, {required int column, required bool useMale}) =>
      seconds <= maxSeconds(column: column, useMale: useMale);
}

/// Who is being scored.
class PtProfile {
  final int age;
  final Sex sex;
  final StandardType standard;

  const PtProfile({
    required this.age,
    required this.sex,
    required this.standard,
  });
}

class EventScore {
  final PtEvent event;
  final int raw;
  final int points;
  final bool passed;

  const EventScore({
    required this.event,
    required this.raw,
    required this.points,
    required this.passed,
  });
}

class PtResult {
  final List<EventScore> events;
  final int total;
  final int minTotal;
  final int minPerEvent;

  const PtResult({
    required this.events,
    required this.total,
    required this.minTotal,
    required this.minPerEvent,
  });

  List<EventScore> get failedEvents => events.where((e) => !e.passed).toList();

  bool get totalMet => total >= minTotal;

  /// A pass needs the minimum in every event and the minimum total.
  bool get passed => failedEvents.isEmpty && totalMet;
}

class PtStandard {
  final String id;
  final String name;
  final String shortName;
  final DateTime effective;
  final String sourceTitle;
  final String sourceUrl;
  final int minPointsPerEvent;
  final int minTotalGeneral;
  final int minTotalCombat;
  final List<String> combatMos;
  final List<String> notes;
  final List<AgeGroup> ageGroups;
  final List<PtEvent> events;
  final List<AlternateEvent> alternates;

  const PtStandard({
    required this.id,
    required this.name,
    required this.shortName,
    required this.effective,
    required this.sourceTitle,
    required this.sourceUrl,
    required this.minPointsPerEvent,
    required this.minTotalGeneral,
    required this.minTotalCombat,
    required this.combatMos,
    required this.notes,
    required this.ageGroups,
    required this.events,
    required this.alternates,
  });

  factory PtStandard.fromJson(Map<String, dynamic> json) {
    final minTotal = json['minTotal'] as Map<String, dynamic>;
    final source = json['source'] as Map<String, dynamic>;
    return PtStandard(
      id: json['id'],
      name: json['name'],
      shortName: json['shortName'],
      effective: DateTime.parse(json['effective']),
      sourceTitle: source['title'],
      sourceUrl: source['url'],
      minPointsPerEvent: json['minPointsPerEvent'],
      minTotalGeneral: minTotal['general'],
      minTotalCombat: minTotal['combat'],
      combatMos: (json['combatMos'] as List).cast<String>(),
      notes: (json['notes'] as List).cast<String>(),
      ageGroups: (json['ageGroups'] as List)
          .map((g) => AgeGroup.fromJson(g as Map<String, dynamic>))
          .toList(),
      events: (json['events'] as List)
          .map((e) => PtEvent.fromJson(e as Map<String, dynamic>))
          .toList(),
      alternates: (json['alternates'] as List)
          .map((a) => AlternateEvent.fromJson(a as Map<String, dynamic>))
          .toList(),
    );
  }

  PtEvent event(String id) => events.firstWhere((e) => e.id == id);

  /// Index of the age group for [age], or null if below the youngest group.
  int? ageColumn(int age) {
    final i = ageGroups.indexWhere((g) => g.contains(age));
    return i == -1 ? null : i;
  }

  bool isCombatMos(String mos) => combatMos.contains(mos.trim().toUpperCase());

  int minTotal(StandardType type) =>
      type == StandardType.combat ? minTotalCombat : minTotalGeneral;

  /// The combat standard is sex-neutral and uses the male/combat column.
  static bool usesMaleColumn(PtProfile p) =>
      p.standard == StandardType.combat || p.sex == Sex.male;

  EventScore scoreEvent(PtEvent event, int raw, PtProfile profile) {
    final column = ageColumn(profile.age);
    if (column == null) {
      throw ArgumentError('No $shortName age group for age ${profile.age}');
    }
    final points = event.score(
      raw,
      column: column,
      useMale: usesMaleColumn(profile),
    );
    return EventScore(
      event: event,
      raw: raw,
      points: points,
      passed: points >= minPointsPerEvent,
    );
  }

  /// Scores the events in [raw] (event id -> lbs/reps/seconds).
  PtResult score(Map<String, int> raw, PtProfile profile) {
    final scores = [
      for (final event in events)
        if (raw[event.id] case final int value)
          scoreEvent(event, value, profile),
    ];
    return PtResult(
      events: scores,
      total: scores.fold(0, (sum, s) => sum + s.points),
      minTotal: minTotal(profile.standard),
      minPerEvent: minPointsPerEvent,
    );
  }
}
